### ISSUE TITLE
error installing Essentials for R (SPSS 23): installation not found

### ISSUE THREAD

**Issue by keunes** [IBMPredictiveAnalytics/R_Essentials_Statistics#1]
Via "https://github.com/IBMPredictiveAnalytics/R_Essentials_Statistics/releases/download/23.0/SPSS_Statistics_R_Essentials_23.0_win64.exe" I've downloaded R Essentials for SPSS 23. I already have R 3.3.1 installed in "C:\Program Files\R\R-3.3.1\bin\x64"
Yet in the installation process the R Essentials says "R 3.1 was not found in this location. Please choose a different location" Is R Essentials 23 not compatible with R 3.3 and should I downgrade R, or are the two compatible and should R Essentials be updated to accept R 3.3 installations?

**Comment by JKPeck** [comment]
Each version of the R Essentials has to be compiled against a specific version of R, so you need to install R3.1.x for V23.  You can have many versions of R installed (I have six.)  Typically each release of Statistics and the R Essentials uses the latest stable version at the time the release is closed.  For V24, that is R3.2 and for V23, it is R3.1.

**Comment by keunes** [comment]
Thanks for the quick reply! Managed to install everything properly in the meantime.
