### ISSUE TITLE
Issue with download on Mac

### ISSUE THREAD

**Issue by loehram** [IBMPredictiveAnalytics/R_Essentials_Statistics#2]
When I double-clicked the file after it downloaded (SPSS_Statistics_R_Essentials_24_Mac.dmg), a box popped up briefly that I could not read that appeared like something was loading and then nothing happened. Tried downloading again and experienced the same issue.

**Comment by Wenpei** [comment]
Jia zhong, Please take a look.

**Comment by wujiazhong** [comment]
Download the file and double-click it. It can be seen in 'Devices' on Macbook as below.
![7fea811a033902c7](https://cloud.githubusercontent.com/assets/11980514/21514157/dd052dfc-ccfc-11e6-99d3-e44040f8ce20.jpg)

Then click the device, entering the device where you should see the file 'SPSS_Statistics_R_Essentials_24_Mac'. Double-click to install.
